-- ================================================================
-- FINAL DATABASE SCHEMA
-- Note: Structure only, no seed data.
-- ================================================================

-- ================================================================
-- PHẦN 0: DỌN DẸP (RESET TOÀN BỘ)
-- ================================================================
DROP TABLE IF EXISTS contact_messages CASCADE;
DROP TABLE IF EXISTS refund_requests CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS cart_items CASCADE;
DROP TABLE IF EXISTS bundle_items CASCADE;
DROP TABLE IF EXISTS bundles CASCADE;
DROP TABLE IF EXISTS product_variants CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;

-- ================================================================
-- PHẦN 1: NGƯỜI DÙNG & PROFILES
-- ================================================================
CREATE TABLE profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name text,
  avatar_url text DEFAULT 'https://placehold.co/100',
  phone text,
  address text,
  role text DEFAULT 'customer',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Bật RLS Profiles
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public profiles are viewable by everyone" ON profiles;
CREATE POLICY "Public profiles are viewable by everyone" ON profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can insert their own profile" ON profiles;
CREATE POLICY "Users can insert their own profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update own profile" ON profiles;
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

-- TRIGGER TỰ ĐỘNG TẠO PROFILE KHI ĐĂNG KÝ
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url, role)
  VALUES (
    new.id, 
    new.raw_user_meta_data->>'full_name', 
    'https://placehold.co/100',
    'customer'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ================================================================
-- PHẦN 2: SẢN PHẨM & DANH MỤC
-- ================================================================
CREATE TABLE categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  image_url text,
  parent_id bigint REFERENCES categories(id) ON DELETE SET NULL, -- Hỗ trợ danh mục cha/con
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index cho parent_id để query danh mục con nhanh hơn
CREATE INDEX IF NOT EXISTS idx_categories_parent ON categories(parent_id);

CREATE TABLE products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id bigint REFERENCES categories(id) ON DELETE SET NULL,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  usage_instruction text, 
  image_url text,
  is_featured boolean DEFAULT false, -- Đánh dấu sản phẩm nổi bật
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE product_variants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint REFERENCES products(id) ON DELETE CASCADE,
  type text NOT NULL CHECK (type IN ('new', 'near_date')), 
  price numeric NOT NULL,
  original_price numeric,
  stock_quantity integer DEFAULT 0,
  expiry_date date, 
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Bật RLS
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_variants ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read Categories" ON categories;
CREATE POLICY "Public Read Categories" ON categories FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read Products" ON products;
CREATE POLICY "Public Read Products" ON products FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read Variants" ON product_variants;
CREATE POLICY "Public Read Variants" ON product_variants FOR SELECT USING (true);

-- ================================================================
-- PHẦN 3: GÓI COMBO (BUNDLES)
-- ================================================================
CREATE TABLE bundles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  price numeric NOT NULL,
  original_price numeric,
  image_url text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE bundle_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bundle_id bigint REFERENCES bundles(id) ON DELETE CASCADE,
  product_variant_id bigint REFERENCES product_variants(id) ON DELETE CASCADE,
  quantity integer DEFAULT 1
);

-- Bật RLS
ALTER TABLE bundles ENABLE ROW LEVEL SECURITY;
ALTER TABLE bundle_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read Bundles" ON bundles;
CREATE POLICY "Public Read Bundles" ON bundles FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read Bundle Items" ON bundle_items;
CREATE POLICY "Public Read Bundle Items" ON bundle_items FOR SELECT USING (true);

-- ================================================================
-- PHẦN 4: GIỎ HÀNG & ĐƠN HÀNG
-- ================================================================
CREATE TABLE cart_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users NOT NULL,
  product_variant_id bigint REFERENCES product_variants(id) ON DELETE CASCADE,
  bundle_id bigint REFERENCES bundles(id) ON DELETE CASCADE,
  quantity integer DEFAULT 1,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users NOT NULL,
  full_name text NOT NULL,
  phone_number text NOT NULL,
  address text NOT NULL,
  note text,
  total_price numeric NOT NULL,
  status text DEFAULT 'pending',
  payment_method text DEFAULT 'cod',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE order_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint REFERENCES orders(id) ON DELETE CASCADE,
  product_variant_id bigint REFERENCES product_variants(id),
  bundle_id bigint REFERENCES bundles(id),
  product_name text NOT NULL, 
  quantity integer NOT NULL,
  price numeric NOT NULL, 
  metadata jsonb 
);

-- Bật RLS
ALTER TABLE cart_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can manage own cart" ON cart_items;
CREATE POLICY "Users can manage own cart" ON cart_items FOR ALL USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view own orders" ON orders;
CREATE POLICY "Users can view own orders" ON orders FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can create orders" ON orders;
CREATE POLICY "Users can create orders" ON orders FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view own order items" ON order_items;
CREATE POLICY "Users can view own order items" ON order_items FOR SELECT USING (
  EXISTS (SELECT 1 FROM orders WHERE orders.id = order_items.order_id AND orders.user_id = auth.uid())
);

DROP POLICY IF EXISTS "Users can create order items" ON order_items;
CREATE POLICY "Users can create order items" ON order_items FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM orders WHERE orders.id = order_items.order_id AND orders.user_id = auth.uid())
);

-- ================================================================
-- PHẦN 5: ĐÁNH GIÁ (REVIEWS)
-- ================================================================
CREATE TABLE reviews (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES profiles(id) ON DELETE CASCADE NOT NULL, 
  product_id bigint REFERENCES products(id) ON DELETE CASCADE NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read Reviews" ON reviews;
CREATE POLICY "Public Read Reviews" ON reviews FOR SELECT USING (true);

DROP POLICY IF EXISTS "Authenticated Users Insert Reviews" ON reviews;
CREATE POLICY "Authenticated Users Insert Reviews" ON reviews FOR INSERT WITH CHECK (auth.uid() = user_id);

-- ================================================================
-- PHẦN 6: HỖ TRỢ & LIÊN HỆ
-- ================================================================
CREATE TABLE refund_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users NOT NULL,
  order_id text NOT NULL,
  reason text NOT NULL,
  image_url text,
  status text DEFAULT 'pending',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE refund_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own refunds" ON refund_requests;
CREATE POLICY "Users can view own refunds" ON refund_requests FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert refunds" ON refund_requests;
CREATE POLICY "Users can insert refunds" ON refund_requests FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE TABLE contact_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL,
  phone text,
  subject text,
  message text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE contact_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can insert messages" ON contact_messages;
CREATE POLICY "Anyone can insert messages" ON contact_messages FOR INSERT WITH CHECK (true);

-- ================================================================
-- PHẦN 7: STORAGE (BUCKET CONFIGURATION)
-- ================================================================

-- 7.1 Bucket 'refunds' (Cho việc hoàn tiền)
INSERT INTO storage.buckets (id, name, public) 
VALUES ('refunds', 'refunds', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Authenticated users can upload refund images" ON storage.objects;
CREATE POLICY "Authenticated users can upload refund images" ON storage.objects 
FOR INSERT WITH CHECK (bucket_id = 'refunds' AND auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Public can view refund images" ON storage.objects;
CREATE POLICY "Public can view refund images" ON storage.objects 
FOR SELECT USING (bucket_id = 'refunds');

-- 7.2 Bucket 'products' (Cho ảnh sản phẩm/combo/danh mục)
INSERT INTO storage.buckets (id, name, public) 
VALUES ('products', 'products', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Public Read Products" ON storage.objects;
CREATE POLICY "Public Read Products" ON storage.objects 
FOR SELECT USING (bucket_id = 'products');

-- Cho phép authenticated user (admin/staff) upload ảnh sản phẩm
DROP POLICY IF EXISTS "Authenticated users can upload product images" ON storage.objects;
CREATE POLICY "Authenticated users can upload product images" ON storage.objects 
FOR INSERT WITH CHECK (bucket_id = 'products' AND auth.role() = 'authenticated');