-- 1. Thêm cột recipes (JSONB) vào bảng products
ALTER TABLE products
ADD COLUMN recipes JSONB DEFAULT NULL;
-- Cập nhật Dồi thịt heo
UPDATE products SET recipes = '{"title": "2 Công Thức Dồi Thịt Heo Ngon Chuẩn Quán Nhậu", "items": [{"name": "Món 1: Dồi Thịt Heo Chiên Giòn", "instruction": "<b>Khẩu phần:</b> 2–3 người\n<b>Thời gian:</b> 15 phút\n<b>Nguyên liệu:</b>\n• 1 gói Dồi thịt heo 200g\n• 300ml dầu ăn (chiên ngập)\n• 1/2 muỗng cà phê muối\n• 1/2 muỗng tiêu\n• Dưa leo, rau răm ăn kèm\n<b>Cách làm:</b>\n• Rã đông tự nhiên 10 phút (không ngâm nước nóng).\n• Dùng tăm châm nhẹ vài lỗ nhỏ để tránh nổ khi chiên.\n• Làm nóng dầu ở 170–175°C.\n• Chiên 5–7 phút đến khi vàng đều, vỏ căng bóng.\n• Vớt ra để ráo dầu 2 phút rồi cắt khúc 3–4cm.\n<b>Mẹo ngon:</b> Chiên 2 lần (mỗi lần 3–4 phút) để vỏ giòn lâu hơn."}, {"name": "Món 2: Dồi Hấp Hành Gừng", "instruction": "<b>Nguyên liệu:</b>\n• 1 gói dồi 200g\n• 15g gừng thái sợi\n• 20g hành lá\n• 1 muỗng canh nước tương\n• 1 muỗng dầu mè\n<b>Cách làm:</b>\n• Hấp dồi 8 phút lửa lớn.\n• Rưới nước tương + dầu mè.\n• Phủ hành, gừng lên trên.\n• Hấp thêm 2 phút.\n• Món này thanh vị, không dầu mỡ, hợp ăn cùng cơm nóng."}]}' WHERE slug = 'doi-thit-heo-200gr';

-- Cập nhật Heo 2 lát
UPDATE products SET recipes = '{"title": "Công Thức Heo 2 Lát Áp Chảo Sốt Tiêu Đen", "items": [{"name": "Hướng dẫn chế biến", "instruction": "<b>Khẩu phần:</b> 1–2 người\n<b>Thời gian:</b> 12 phút\n<b>Nguyên liệu:</b>\n• 150g heo 2 lát\n• 1 muỗng dầu hào\n• 1/2 muỗng đường\n• 1 muỗng tiêu đen\n• 1 muỗng nước lọc\n• 1 muỗng dầu ăn\n<b>Cách làm:</b>\n• Làm nóng chảo với dầu ăn.\n• Áp chảo mỗi mặt 3 phút lửa vừa.\n• Trộn dầu hào + đường + nước + tiêu → đổ vào chảo.\n• Rim thêm 2–3 phút cho sốt sệt lại.\n<b>Mẹo:</b> Không lật thịt quá nhiều để giữ độ mềm."}]}' WHERE slug = 'heo-2-lat-150gr';

-- Cập nhật Xíu mại
UPDATE products SET recipes = '{"title": "Công Thức Xíu Mại Sốt Cà Chuẩn Vị – Ăn Với Bánh Mì Cực Đỉnh", "items": [{"name": "Hướng dẫn chế biến", "instruction": "<b>Khẩu phần:</b> 3–4 người\n<b>Thời gian:</b> 20 phút\n<b>Nguyên liệu:</b>\n• 1 gói xíu mại\n• 200ml sốt cà chua\n• 1/2 củ hành tây (50g)\n• 1 muỗng tương cà\n• 1 muỗng nước mắm\n• 1/2 muỗng đường\n• 100ml nước\n<b>Cách làm:</b>\n• Phi hành tây với 1 muỗng dầu ăn.\n• Cho sốt cà + nước + gia vị vào nấu sôi.\n• Thả xíu mại vào, đậy nắp.\n• Nấu lửa nhỏ 10–12 phút cho thấm."}]}' WHERE slug = 'xiu-mai-xot-ca';

-- Cập nhật Pate thịt heo
UPDATE products SET recipes = '{"title": "3 Cách Biến Tấu Pate Thịt Heo – Không Chỉ Là Pate Bánh Mì", "items": [{"name": "Món 1: Pate Sốt Tiêu Đen Đậm Đà Ăn Cơm", "instruction": "<b>Khẩu phần:</b> 2–3 người\n<b>Thời gian:</b> 7–10 phút\n<b>Nguyên liệu:</b>\n• 170g pate thịt heo\n• 60ml nước lọc\n• 1 muỗng cà phê tiêu đen xay\n• 1 muỗng canh hành tím băm\n• 1 muỗng cà phê dầu ăn\n• 1/2 muỗng cà phê nước mắm\n• 1/2 muỗng cà phê đường\n<b>Cách làm:</b>\n• Phi thơm hành tím với dầu ăn ở lửa vừa.\n• Cho pate vào đảo nhẹ tay 1–2 phút.\n• Thêm nước lọc để pate mềm mịn hơn.\n• Nêm nước mắm + đường + tiêu đen.\n• Rim lửa nhỏ 3–5 phút đến khi sốt sánh lại."}, {"name": "Món 2: Trứng Hấp Pate Mềm Mịn", "instruction": "<b>Khẩu phần:</b> 2 người\n<b>Thời gian:</b> 15 phút\n<b>Nguyên liệu:</b>\n• 2 quả trứng gà\n• 70–80g pate\n• 100ml nước ấm (tỉ lệ 1 trứng : 50ml nước)\n• 1/3 muỗng cà phê muối\n• Hành lá hoặc tiêu xay\n<b>Cách làm:</b>\n• Đánh tan trứng với nước ấm và muối.\n• Tán nhỏ pate rồi trộn vào hỗn hợp trứng.\n• Lọc qua rây để hỗn hợp mịn.\n• Hấp lửa vừa 12–15 phút.\n• Rắc hành lá hoặc tiêu trước khi dùng.\n<b>Mẹo:</b> Phủ khăn hoặc màng bọc lên miệng chén để mặt trứng mịn, không rỗ."}, {"name": "Món 3: Bánh Mì Pate Áp Chảo Giòn Tan", "instruction": "<b>Khẩu phần:</b> 2–3 người\n<b>Thời gian:</b> 10 phút\n<b>Nguyên liệu:</b>\n• 1 ổ bánh mì hoặc 4 lát sandwich\n• 100g pate\n• 10g bơ lạt\n• 2 lát dưa leo\n• 1 ít đồ chua (cà rốt, củ cải)\n• Tương ớt hoặc mayonnaise\n<b>Cách làm:</b>\n• Phết bơ lên mặt bánh mì.\n• Áp chảo 2 mặt đến vàng giòn.\n• Phết pate dày khoảng 20–25g mỗi phần.\n• Thêm dưa leo, đồ chua và sốt tùy thích.\n<b>Thành phẩm:</b> Vỏ bánh giòn, pate béo mịn, kết hợp vị chua nhẹ cực cân bằng."}]}' WHERE slug = 'pate-thit-heo-170gr';

-- Cập nhật Sườn nấu đậu
UPDATE products SET recipes = '{"title": "Công Thức Sườn Nấu Đậu Nóng Hổi – Bữa Cơm Gia Đình Ấm Áp", "items": [{"name": "Hướng dẫn chế biến", "instruction": "<b>Khẩu phần:</b> 2–3 người\n<b>Thời gian:</b> 15–20 phút\n<b>Nguyên liệu:</b>\n• 1 gói Sườn nấu đậu 170GR\n• 300ml nước (có thể tăng 400ml nếu thích nhiều nước)\n• 80g đậu trắng hoặc đậu Hà Lan (tùy chọn thêm)\n• 1 quả cà chua (70–80g), cắt múi\n• 1 muỗng cà phê hành tím băm\n• 1/2 muỗng cà phê muối (tùy khẩu vị)\n• 1/2 muỗng cà phê đường\n• 1 ít tiêu xay\n• 10g hành lá, ngò rí\n<b>Cách làm:</b>\n<b>Bước 1:</b> Chuẩn bị\n• Nếu dùng thêm đậu khô, ngâm trước 2–3 giờ cho mềm.\n• Rã đông sườn tự nhiên 10–15 phút.\n<b>Bước 2:</b> Nấu canh\n• Đun sôi 300ml nước trong nồi.\n• Cho sườn vào nấu lửa vừa 5 phút.\n• Thêm đậu (nếu có) và cà chua vào.\n• Nêm muối + đường cho vị hài hòa.\n• Nấu thêm 8–10 phút đến khi đậu mềm, sườn nóng đều.\n<b>Bước 3:</b> Hoàn thiện\n• Tắt bếp, rắc tiêu xay và hành lá.\n• Dùng ngay khi còn nóng.\n<b>Mẹo giúp món ngon hơn:</b>\n• Thêm 1 lát gừng mỏng nếu muốn vị thanh nhẹ.\n• Nếu thích vị đậm hơn, có thể cho 1 muỗng nước mắm khi gần tắt bếp.\n• Có thể nấu đặc như súp bằng cách giảm lượng nước còn 200–250ml."}]}' WHERE slug = 'suon-nau-dau-170gr';

-- Cập nhật Bò viên
UPDATE products SET recipes = '{"title": "🥩 Top 3 Món Ngon Với Bò Viên – Chiên, Xào, Nấu Lẩu", "items": [{"name": "Món 1: Bò Viên Chiên Nước Mắm Tỏi", "instruction": "<b>Thời gian:</b> 12 phút\n<b>Nguyên liệu:</b>\n• 300g bò viên\n• 2 muỗng canh nước mắm\n• 1 muỗng canh đường\n• 1 muỗng cà phê tương ớt (tuỳ thích)\n• 1 muỗng cà phê tỏi băm\n• 2 muỗng canh dầu ăn\n<b>Cách làm:</b>\n• Làm nóng chảo với 2 muỗng dầu ăn.\n• Cho bò viên vào chiên lửa vừa 4–5 phút đến khi vàng nhẹ, vỏ hơi xém.\n• Pha hỗn hợp: nước mắm + đường + tương ớt.\n• Phi thơm tỏi riêng, sau đó đổ hỗn hợp nước mắm vào.\n• Cho bò viên vào đảo đều 2–3 phút đến khi sốt sệt và áo đều."}, {"name": "Món 2: Bò Viên Xào Rau Củ", "instruction": "<b>Thời gian:</b> 10–12 phút\n<b>Nguyên liệu:</b>\n• 250g bò viên (cắt đôi)\n• 1/2 củ hành tây (50g)\n• 1/2 trái ớt chuông (50g)\n• 50g cải ngọt hoặc bông cải\n• 1 muỗng canh dầu hào\n• 1/2 muỗng cà phê tiêu\n• 1 muỗng canh dầu ăn\n<b>Cách làm:</b>\n• Phi nóng dầu, cho bò viên vào xào 2–3 phút.\n• Thêm rau củ, đảo nhanh tay lửa lớn 3–4 phút.\n• Nêm dầu hào và tiêu, đảo đều thêm 1–2 phút.\n• Tắt bếp khi rau còn độ giòn.\n<b>Mẹo:</b> Xào lửa lớn và nhanh tay để rau giữ màu đẹp và không ra nước."}, {"name": "Món 3: Bò Viên Nấu Lẩu / Hủ Tiếu", "instruction": "<b>Thời gian:</b> 15–20 phút\n<b>Nguyên liệu:</b>\n• 200–300g bò viên\n• 1 lít nước dùng xương hoặc nước lẩu\n• 1 muỗng cà phê muối\n• 1/2 muỗng cà phê đường phèn\n• Hành lá, ngò rí\n• Bún, hủ tiếu hoặc mì\n<b>Cách làm:</b>\n• Đun sôi nước dùng.\n• Nêm muối và đường phèn cho vị thanh ngọt.\n• Thả bò viên vào, nấu 5–7 phút đến khi nổi lên.\n• Chan nước dùng và bò viên lên bún/hủ tiếu.\n• Rắc hành ngò, thêm tiêu hoặc ớt sa tế tuỳ khẩu vị.\n<b>Thành phẩm:</b> Bò viên dai ngon, nước dùng ngọt thanh – ăn nóng là “đúng bài”."}]}' WHERE slug = 'bo-vien-05kg';

-- Cập nhật Chạo bò
UPDATE products SET recipes = '{"title": "🌶 Công Thức Chạo Bò Nướng & Chiên Giòn – Ăn Là Ghiền", "items": [{"name": "Món 1: Chạo Bò Nướng Sả Thơm Lừng", "instruction": "<b>Thời gian:</b> 20–25 phút (tính cả nướng)\n<b>Nguyên liệu:</b>\n• 500g chạo bò\n• 3 cây sả (băm nhuyễn phần gốc trắng ~30g)\n• 1 muỗng cà phê tỏi băm\n• 1/2 muỗng cà phê tiêu xay\n• 1 muỗng cà phê dầu điều (tạo màu đẹp)\n• 1 muỗng cà phê mật ong (giúp mặt nướng bóng nhẹ)\n<b>Cách làm:</b>\n<b>Bước 1:</b> Trộn gia vị\n• Trộn chạo bò với sả băm, tỏi, tiêu, dầu điều và mật ong.\n• Để nghỉ 10 phút cho thấm vị.\n<b>Bước 2:</b> Tạo hình & nướng\n• Vo thành từng viên dẹt hoặc bọc quanh cây sả.\n• Nướng lò ở 180°C trong 15–18 phút.\n• Lật mặt sau 8–10 phút để vàng đều.\n<b>Thành phẩm:</b> Bên ngoài xém nhẹ, bên trong mềm ẩm, thơm mùi sả – ăn kèm rau sống và nước mắm chua ngọt là “hết sẩy”.\n<b>Mẹo:</b> Nếu nướng than, trở đều tay để tránh cháy cạnh."}, {"name": "Món 2: Chạo Bò Chiên Giòn Đậm Vị", "instruction": "<b>Thời gian:</b> 12–15 phút\n<b>Nguyên liệu:</b>\n• 300–500g chạo bò\n• 300ml dầu ăn (chiên ngập)\n• 1/2 muỗng cà phê tiêu\n• Ớt bột (tuỳ khẩu vị)\n<b>Cách làm:</b>\n• Cắt chạo bò thành lát dày 1–1.5cm hoặc viên tròn nhỏ.\n• Làm nóng dầu ở 170–175°C.\n• Chiên 4–6 phút đến khi vàng đều.\n• Vớt ra để ráo dầu 1–2 phút.\n• Rắc thêm tiêu hoặc ớt bột nếu thích cay.\n<b>Thành phẩm:</b> Lớp ngoài vàng giòn, bên trong dai mềm, đậm vị bò – ăn với tương ớt hoặc tương đen đều hợp.\n<b>Mẹo giòn lâu:</b> Chiên 2 lần – lần 1 chín 70%, để nguội 3 phút rồi chiên lại 1–2 phút."}]}' WHERE slug = 'chao-bo-500gr';

-- Cập nhật Bò viên ngon Cầu Tre
UPDATE products SET recipes = '{"title": "🔥 2 Công Thức Chuẩn Vị Với Bò Viên Ngon Cầu Tre – Đậm Đà, Dai Ngon", "items": [{"name": "Món 1: Bò Viên Sốt Sa Tế Cay Nhẹ – Ăn Là Ghiền", "instruction": "<b>Thời gian:</b> 12–15 phút\n<b>Nguyên liệu:</b>\n• 300g bò viên (cắt đôi nếu viên lớn)\n• 1 muỗng canh sa tế\n• 1 muỗng canh dầu hào\n• 1 muỗng cà phê đường\n• 50ml nước lọc\n• 1 muỗng cà phê tỏi băm\n• 1 muỗng canh dầu ăn\n<b>Cách làm:</b>\n• Làm nóng chảo với dầu ăn, phi thơm tỏi.\n• Cho bò viên vào đảo 2–3 phút cho săn mặt.\n• Thêm sa tế + dầu hào + đường + nước lọc.\n• Rim lửa vừa 3–5 phút đến khi sốt sệt và áo đều quanh viên bò.\n• Nếm lại cho vừa khẩu vị, có thể thêm ớt nếu thích cay hơn.\n<b>Thành phẩm:</b> Bò viên dai giòn, thấm vị cay nhẹ, màu đỏ đẹp mắt – ăn với cơm nóng hoặc làm món nhâm nhi đều hợp.\n<b>Mẹo:</b> Nếu muốn sốt sánh hơn, có thể pha thêm 1/2 muỗng cà phê bột bắp với 1 muỗng nước rồi cho vào cuối cùng."}, {"name": "Món 2: Bò Viên Nấu Hủ Tiếu / Phở Thanh Ngọt", "instruction": "<b>Thời gian:</b> 15–20 phút\n<b>Nguyên liệu:</b>\n• 200–300g bò viên\n• 1 lít nước dùng xương (hoặc nước lọc + 1 viên gia vị)\n• 1/2 muỗng cà phê muối\n• 1/2 muỗng cà phê đường phèn\n• 1 muỗng cà phê nước mắm\n• Hành lá, ngò rí\n• Hủ tiếu hoặc bánh phở\n<b>Cách làm:</b>\n• Đun sôi nước dùng.\n• Nêm muối, đường phèn và nước mắm cho vị thanh ngọt.\n• Thả bò viên vào nấu 5–7 phút đến khi nổi lên.\n• Trụng hủ tiếu/phở riêng trong nước sôi 1 phút.\n• Chan nước dùng và bò viên lên tô, thêm hành ngò và tiêu.\n<b>Thành phẩm:</b> Nước dùng trong, vị ngọt tự nhiên; bò viên dai mềm, thơm thịt bò đặc trưng.\n<b>Mẹo ngon:</b> Có thể thêm vài lát gừng nướng vào nước dùng để tăng hương thơm."}]}' WHERE slug = 'bo-vien-cau-tre-500gr';

-- Cập nhật Tôm Surimi
UPDATE products SET recipes = '{"title": "Món “Gây Nghiện” Từ Tôm Surimi – 10 Phút Là Có Ngay Món Ngon", "items": [{"name": "Hướng dẫn chế biến", "instruction": "Tôm Surimi Chiên Xù Giòn Tan\n<b>Khẩu phần:</b> 3 người\n<b>Thời gian:</b> 15 phút\n<b>Nguyên liệu:</b>\n• 300g tôm surimi\n• 1 quả trứng\n• 50g bột chiên xù\n• 30g bột chiên giòn\n• 300ml dầu ăn\n<b>Cách làm:</b>\n• Cắt surimi thành khúc vừa ăn (3–4cm).\n• Lăn qua bột chiên giòn khô → nhúng trứng → lăn bột xù.\n• Làm nóng dầu 170–175°C.\n• Chiên 3–4 phút đến khi vàng đều.\n• Vớt ra để ráo dầu 1 phút trước khi dùng.\n• Giòn bên ngoài – dai mềm bên trong."}]}' WHERE slug = 'tom-surimi-500g';

-- Cập nhật Tôm viên 1kg
UPDATE products SET recipes = '{"title": "Top 2 Món Ngon “Bắt Cơm – Bắt Mồi” Với Tôm Viên", "items": [{"name": "Món 1: Tôm Viên Chiên Giòn Chấm Tương Ớt – Món Ăn Vặt Quốc Dân", "instruction": "<b>Khẩu phần:</b> 3–4 người\n<b>Thời gian:</b> 15 phút\n<b>Nguyên liệu:</b>\n• 500g tôm viên\n• 400ml dầu ăn\n• Tương ớt hoặc tương cà\n<b>Cách làm:</b>\n• Rã đông tôm viên tự nhiên 10–15 phút (không ngâm nước nóng).\n• Làm nóng dầu ở 170–175°C (thử bằng cách thả 1 viên thấy nổi nhẹ là đạt).\n• Chiên ngập dầu 4–5 phút, đảo nhẹ để vàng đều.\n• Vớt ra để ráo 1–2 phút."}, {"name": "Món 2: Tôm Viên Sốt Me Chua Ngọt", "instruction": "<b>Khẩu phần:</b> 3 người\n<b>Thời gian:</b> 20 phút\n<b>Nguyên liệu:</b>\n• 400g tôm viên\n• 2 muỗng canh nước cốt me\n• 1,5 muỗng canh đường\n• 1 muỗng canh nước mắm\n• 80ml nước lọc\n• 1 muỗng tỏi băm\n• 1/2 muỗng ớt băm\n<b>Cách làm:</b>\n• Chiên sơ tôm viên 3–4 phút cho săn lại.\n• Phi thơm tỏi với 1 muỗng dầu.\n• Cho nước me + đường + nước mắm + nước vào nấu sôi nhỏ lửa.\n• Thêm tôm viên vào đảo đều 3–5 phút đến khi sốt sệt áo quanh viên.\n• Vị chua – ngọt – mặn cân bằng, ăn với cơm nóng cực bắt vị."}]}' WHERE slug = 'tom-vien-1kg';

-- Cập nhật Tôm thẻ đông lạnh
UPDATE products SET recipes = '{"title": "Tôm Thẻ Rim Mặn Ngọt – Nhanh Gọn Mà Đưa Cơm", "items": [{"name": "Hướng dẫn chế biến", "instruction": "<b>Khẩu phần:</b> 3–4 người\n<b>Thời gian:</b> 15 phút\n<b>Nguyên liệu:</b>\n• 0.5kg tôm thẻ (rã đông, cắt râu)\n• 2 muỗng canh nước mắm\n• 1.5 muỗng canh đường\n• 1 muỗng cà phê tiêu\n• 1 củ hành tím băm\n<b>Cách làm:</b>\n• Phi hành thơm, cho tôm vào đảo đều đến khi săn lại (chuyển màu cam).\n• Nêm nước mắm và đường.\n• Rim nhỏ lửa 5–7 phút đến khi cạn nước, vỏ tôm bóng bẩy.\n• Rắc tiêu và hành lá."}]}' WHERE slug = 'tom-the-dong-lanh';

-- Cập nhật Lạp xưởng tôm
UPDATE products SET recipes = '{"title": "Công thức Cơm Chiên Lạp Xưởng Tôm “Chuẩn Quán”", "items": [{"name": "Hướng dẫn chế biến", "instruction": "<b>Khẩu phần:</b> 3 người\n<b>Thời gian:</b> 15 phút\n<b>Nguyên liệu:</b>\n• 200g lạp xưởng tôm (cắt lát mỏng 0,5cm)\n• 2 chén cơm nguội (400g)\n• 2 trứng gà\n• 1 muỗng canh nước mắm\n• 1/2 muỗng cà phê tiêu\n• 2 muỗng dầu ăn\n• Hành lá\n<b>Cách làm:</b>\n• Áp chảo lạp xưởng 4–5 phút lửa vừa cho ra mỡ.\n• Đập trứng vào đảo tơi.\n• Cho cơm vào, xào lửa lớn 3–4 phút.\n• Nêm nước mắm, tiêu.\n• Thêm hành lá, đảo thêm 1 phút rồi tắt bếp.\n• Hạt cơm tơi, béo thơm vị tôm đặc trưng."}]}' WHERE slug = 'lap-xuong-tom-200gr';

-- Cập nhật Cá viên Basa
UPDATE products SET recipes = '{"title": "Công Thức Cá Viên Basa Chiên Nước Mắm Chuẩn Vị – Ăn Vặt Hay Ăn Cơm Đều Cuốn", "items": [{"name": "Hướng dẫn chế biến", "instruction": "<b>Khẩu phần:</b> 3–4 người\n<b>Thời gian:</b> 15 phút\n<b>Nguyên liệu:</b>\n• 400g cá viên basa\n• 300ml dầu ăn\n• 2 muỗng nước mắm\n• 1 muỗng đường\n• 2 muỗng nước\n• 1 muỗng tỏi băm\n<b>Cách làm:</b>\n• Chiên cá viên 170°C trong 4–5 phút.\n• Phi tỏi thơm.\n• Pha nước mắm + đường + nước, đổ vào chảo.\n• Cho cá viên vào rim 2–3 phút đến khi áo sốt.\n• Dai mềm, đậm vị, cực hao cơm."}]}' WHERE slug = 'ca-vien-basa-05kg';

-- Cập nhật Cá viên rau củ
UPDATE products SET recipes = '{"title": "Thèm ăn vặt mà sợ ngán? Thử ngay Cá viên hải sản mix rau củ thanh nhẹ.", "items": [{"name": "Hướng dẫn chế biến", "instruction": "Cá Viên Rau Củ Sốt Mắm Tỏi Chiến Giòn\nMón này vừa có màu sắc xanh đỏ của rau củ ẩn trong viên cá, vừa có lớp sốt óng ánh, thơm lừng vị tỏi phi.\n1. Chuẩn bị:\nCá viên rau củ hải sản: 1 gói 500g.\nGia vị: 2 muỗng canh nước mắm, 2 muỗng canh đường, 1 muỗng canh tương ớt, 1 muỗng cà phê ớt bột.\nTỏi băm thật nhiều (khoảng 2 củ) và hành lá.\n2. Cách làm:\n<b>Bước 1:</b> (Chiên cá): Cho dầu vào chảo, đợi dầu thật nóng thì thả cá viên vào. Chiên đến khi viên cá nở phồng, vàng đều các mặt. Vớt ra để ráo dầu (việc chiên nóng giúp cá viên dai hơn).\n<b>Bước 2:</b> (Phi tỏi): Dùng một chảo khác, cho ít dầu và phi tỏi băm đến khi vàng thơm, vớt bớt 1 phần tỏi phi ra để riêng.\n<b>Bước 3:</b> (Rim sốt): Cho hỗn hợp mắm, đường, tương ớt vào chảo tỏi, nấu đến khi sốt sủi bọt và hơi kẹo lại.\n<b>Bước 4:</b> Trút toàn bộ cá viên vào chảo sốt, đảo nhanh tay ở lửa lớn để sốt bám đều. Cuối cùng rắc hành lá và phần tỏi phi còn lại lên trên."}]}' WHERE slug = 'ca-vien-rau-cu-05kg';

-- Cập nhật Cá viên đậu hũ
UPDATE products SET recipes = '{"title": "Mềm mịn như mây - Đậm đà vị cá: Cá viên kiểu đậu hủ \"tan chảy\" ngay đầu lưỡi.", "items": [{"name": "Hướng dẫn chế biến", "instruction": "CÁ VIÊN ĐẬU HỦ SỐT PHÔ MAI TRỨNG MUỐI\nVì cá viên này có độ mềm mịn như đậu hủ, nó cực kỳ hợp với các loại sốt béo ngậy.\n1. Chuẩn bị:\nCá viên kiểu đậu hủ: 1 gói 200g.\nSốt béo: 1 lòng đỏ trứng muối (hấp chín, tán nhuyễn), 1 miếng phô mai con bò cười, 50ml sữa tươi không đường, 1 muỗng cà phê đường.\nBơ lạt và tỏi băm.\n2. Cách làm:\n<b>Bước 1:</b> (Làm nóng): Chiên sơ cá viên đậu hủ trong dầu nóng hoặc nồi chiên không dầu ở 160°C trong 5 phút. Đừng chiên quá lâu để giữ độ mềm mướt bên trong.\n<b>Bước 2:</b> (Nấu sốt): Phi thơm tỏi với bơ, cho trứng muối vào xào nổi bọt. Thêm sữa tươi và phô mai vào khuấy tan đến khi hỗn hợp sệt lại.\n<b>Bước 3:</b> (Thấm vị): Cho cá viên vào đảo nhẹ tay để sốt phủ đều một lớp vàng óng bên ngoài.\n<b>Bước 4:</b> Thưởng thức khi còn nóng. Cảm giác cắn vào lớp sốt béo ngậy rồi đến phần cá viên mềm tan như đậu hủ cực kỳ kích thích."}]}' WHERE slug = 'ca-vien-dau-hu-200gr';

-- Cập nhật Cá viên lốc xoáy
UPDATE products SET recipes = '{"title": "Mãn nhãn với \"vũ điệu lốc xoáy\" trong chảo dầu – Bạn đã thử chưa?", "items": [{"name": "Hướng dẫn chế biến", "instruction": "🌪️ CÁ VIÊN LỐC XOÁY LẮC PHÔ MAI TRỨNG MUỐI \nTận dụng các khe rãnh của \"lốc xoáy\" để giữ trọn phần bột lắc, tạo nên hương vị bùng nổ.\n1. Chuẩn bị:\nCá viên lốc xoáy: 1 gói 200g.\nBột phô mai (hoặc bột trứng muối): 2 muỗng canh.\nLá hương thảo hoặc lá chanh thái sợi (để tăng mùi thơm).\nDầu ăn.\n2. Cách làm:\n<b>Bước 1:</b> (Chiên nở): Đun dầu thật nóng, thả cá viên lốc xoáy vào. Khi gặp nhiệt độ cao, các vòng xoáy sẽ nở bung ra nhìn rất đẹp mắt. Chiên đến khi vàng đều thì vớt ra để ráo dầu.\n<b>Bước 2:</b> (Lắc vị): Cho cá viên vào một cái hộp hoặc túi giấy. Rắc bột phô mai/trứng muối vào.\n<b>Bước 3:</b> Đậy nắp và lắc thật đều tay. Phần bột sẽ bám sâu vào các khe lốc xoáy, giúp mỗi miếng cắn đều đậm đà.\n<b>Bước 4:</b> Thưởng thức kèm tương ớt hoặc sốt mayonnaise cay."}]}' WHERE slug = 'ca-vien-loc-xoay-200gr';

-- Cập nhật Mực ghim đông lạnh
UPDATE products SET recipes = '{"title": "Mực Ghim Nướng Sa Tế – Đỉnh Cao Tiệc Tùng", "items": [{"name": "Hướng dẫn chế biến", "instruction": "<b>Khẩu phần:</b> 4 người\n<b>Thời gian:</b> 25 phút\n<b>Nguyên liệu:</b>\n• 0.5kg mực ghim (rã đông hoàn toàn)\n• 2 muỗng canh sa tế\n• 1 muỗng canh dầu hào\n• 1 muỗng cà phê đường\n• 1/2 muỗng cà phê tỏi băm\n<b>Cách làm:</b>\n• Trộn đều sa tế, dầu hào, đường, tỏi.\n• Ướp mực 15 phút.\n• Nướng than hoặc nồi chiên không dầu 180°C trong 10-12 phút.\n• Mực giòn sần sật, cay nồng, ăn kèm muối tiêu chanh."}]}' WHERE slug = 'muc-ghim-dong-lanh';

-- Cập nhật Thịt ghẹ 0.5kg
UPDATE products SET recipes = '{"title": "Công Thức Súp Ghẹ Bắp Non Bổ Dưỡng – Ngọt Thanh Tự Nhiên", "items": [{"name": "Hướng dẫn chế biến", "instruction": "Công Thức Súp Ghẹ Bắp Non Bổ Dưỡng – Ngọt Thanh Tự Nhiên\n<b>Khẩu phần:</b> 4 người\n<b>Thời gian:</b> 20 phút\n<b>Nguyên liệu:</b>\n• 300g thịt ghẹ\n• 1 lít nước dùng gà\n• 70g bắp hạt\n• 1 lòng trắng trứng\n• 2 muỗng canh bột bắp + 50ml nước\n• 1 muỗng canh nước mắm\n• 1/2 muỗng cà phê tiêu\n• Ngò rí\n<b>Cách làm:</b>\n• Đun sôi nước dùng, cho bắp vào nấu 5 phút.\n• Thêm thịt ghẹ, nấu 3 phút (không đảo mạnh để giữ sợi ghẹ).\n• Cho bột bắp vào khuấy đều để tạo độ sánh.\n• Đổ lòng trắng trứng theo vòng tròn để tạo vân đẹp.\n• Nêm nước mắm, tiêu vừa ăn.\n• Món khai vị giàu dinh dưỡng, phù hợp cả trẻ nhỏ và người lớn."}]}' WHERE slug = 'thit-ghe-05kg';

-- Cập nhật Xúc xích Cocktail TH
UPDATE products SET recipes = '{"title": "Công Thức Xúc Xích Cocktail Rim Sốt BBQ – Món Nhắm Cực Bắt Vị", "items": [{"name": "Hướng dẫn chế biến", "instruction": "<b>Khẩu phần:</b> 3–4 người\n<b>Thời gian:</b> 12 phút\n<b>Nguyên liệu:</b>\n• 1 gói xúc xích cocktail (250g)\n• 2 muỗng canh sốt BBQ\n• 1 muỗng canh tương cà\n• 1 muỗng cà phê mật ong\n• 1 muỗng dầu ăn\n<b>Cách làm:</b>\n• Áp chảo xúc xích 4–5 phút lửa vừa đến khi vỏ căng bóng.\n• Trộn BBQ + tương cà + mật ong.\n• Đổ sốt vào chảo, đảo nhỏ lửa 2–3 phút cho áo đều.\n• Vị mặn ngọt hài hòa, thích hợp tiệc, ăn vặt, nhâm nhi."}]}' WHERE slug = 'xx-cocktail-th-250gr';

-- Cập nhật Xúc xích xông khói TH
UPDATE products SET recipes = '{"title": "Công Thức Bánh Mì Xúc Xích Xông Khói Chuẩn Vị Đường Phố", "items": [{"name": "Hướng dẫn chế biến", "instruction": "<b>Khẩu phần:</b> 3 người\n<b>Thời gian:</b> 15 phút\n<b>Nguyên liệu:</b>\n• 3 cây xúc xích xông khói\n• 3 ổ bánh mì\n• Dưa leo, đồ chua\n• Tương ớt, mayonnaise\n<b>Cách làm:</b>\n• Áp chảo xúc xích 5–6 phút, lật đều tay.\n• Rạch bánh mì, làm nóng 2 phút.\n• Cho xúc xích vào, thêm rau và sốt.\n• Thơm mùi khói đặc trưng, tiện lợi cho bữa sáng."}]}' WHERE slug = 'xx-xong-khoi-th-450gr';

-- Cập nhật Xúc xích Mortadella
UPDATE products SET recipes = '{"title": "Pizza Xúc Xích Mortadella Siêu Nhanh Bằng Bánh Tráng", "items": [{"name": "Hướng dẫn chế biến", "instruction": "<b>Khẩu phần:</b> 1-2 người\n<b>Thời gian:</b> 10 phút\n<b>Nguyên liệu:</b>\n• 100g xúc xích Mortadella\n• 2 miếng bánh tráng nướng\n• 1 quả trứng cút\n• Phô mai kéo sợi\n• Hành lá, tương ớt, mayonnaise\n<b>Cách làm:</b>\n• Đặt bánh tráng lên chảo, đập trứng cút và tán đều.\n• Rắc xúc xích cắt hạt lựu, hành lá, phô mai lên trên.\n• Nướng lửa nhỏ đến khi phô mai chảy, bánh tráng giòn.\n• Xịt tương ớt và mayo lên. Béo ngậy, chuẩn vị tuổi thơ."}]}' WHERE slug = 'xx-mortadella-200gr';

-- Cập nhật Surimi bánh bao trứng cá
UPDATE products SET recipes = '{"title": "Bánh Bao Trứng Cá Nấu Mì Cay Hàn Quốc", "items": [{"name": "Hướng dẫn chế biến", "instruction": "<b>Khẩu phần:</b> 1 người\n<b>Thời gian:</b> 10 phút\n<b>Nguyên liệu:</b>\n• 100g surimi nhân trứng cá (tầm 4-5 viên)\n• 1 gói mì cay Hàn Quốc\n• Hành baro, kim chi ăn kèm\n• 1 quả trứng gà\n<b>Cách làm:</b>\n• Đun nước sôi, thả viên surimi vào nấu 3 phút.\n• Cho mì và gia vị vào nấu thêm 3 phút.\n• Đập trứng, thêm kim chi, hành baro.\n• Viên surimi cắn vào nổ lách tách, béo ngậy, giảm độ gắt của mì cay."}]}' WHERE slug = 'surimi-nhan-hai-san';

-- Cập nhật Chả giò hải sản đặc biệt
UPDATE products SET recipes = '{"title": "Mẹo Chiên Chả Giò Hải Sản Giòn Lâu Đến 4 Tiếng", "items": [{"name": "Hướng dẫn chế biến", "instruction": "<b>Khẩu phần:</b> 3-4 người\n<b>Thời gian:</b> 20 phút\n<b>Nguyên liệu:</b>\n• 1 gói chả giò hải sản 500g\n• Dầu ăn\n• 1 muỗng cà phê nước cốt chanh\n<b>Cách làm:</b>\n• Đổ dầu ngập 1/2 cuốn chả, đun nóng vừa.\n• Vắt nước cốt chanh vào chảo dầu (bí quyết giúp chả giòn lâu và không bắn dầu).\n• Cho chả giò vào chiên (KHÔNG rã đông) ở lửa nhỏ 10 phút.\n• Vớt ra thấm dầu. Bật lửa lớn, thả vào chiên lần 2 khoảng 2 phút đến khi vàng ruộm.\n• Chấm kèm sốt mayonnaise pha tương ớt."}]}' WHERE slug = 'cha-gio-hai-san-dac-biet';

-- Cập nhật Chả giò nhân thịt
UPDATE products SET recipes = '{"title": "Bún Chả Giò Thịt Nướng Siêu Tốc Cho Ngày Lười", "items": [{"name": "Hướng dẫn chế biến", "instruction": "<b>Khẩu phần:</b> 2 người\n<b>Thời gian:</b> 20 phút\n<b>Nguyên liệu:</b>\n• 8 cuốn chả giò nhân thịt\n• 300g bún tươi\n• Rau sống, dưa leo băm nhỏ, đậu phộng rang\n• Nước mắm tỏi ớt chua ngọt\n<b>Cách làm:</b>\n• Chiên chả giò vàng giòn, cắt làm đôi.\n• Xếp rau sống, bún, chả giò vào tô.\n• Rắc đậu phộng, rưới nước mắm chua ngọt.\n• Trộn đều và thưởng thức bữa trưa nhanh gọn, đủ chất."}]}' WHERE slug = 'cha-gio-nhan-thit';

-- Cập nhật Chả giò chay
UPDATE products SET recipes = '{"title": "Gỏi Cuốn Chả Giò Chay Thanh Mát Lạ Miệng", "items": [{"name": "Hướng dẫn chế biến", "instruction": "<b>Khẩu phần:</b> 2-3 người\n<b>Thời gian:</b> 25 phút\n<b>Nguyên liệu:</b>\n• 10 cuốn chả giò chay (chiên giòn)\n• 10 miếng bánh tráng\n• Rau xà lách, tía tô, húng quế\n• Bún tươi\n• Tương đen hoặc bơ đậu phộng pha loãng\n<b>Cách làm:</b>\n• Làm ướt bánh tráng, trải rau sống và bún lên.\n• Đặt nguyên 1 cuốn chả giò chay đã chiên vào giữa.\n• Cuộn chặt tay.\n• Chấm kèm sốt tương đen béo ngậy. Ăn chay thanh đạm nhưng giòn rụm bắt miệng."}]}' WHERE slug = 'cha-gio-chay';

-- Cập nhật Giò lụa
UPDATE products SET recipes = '{"title": "Chỉ với 1 cây giò nhỏ: Biến tấu 2 món ngon khó cưỡng cho cả gia đình.", "items": [{"name": "Món 1: GIÒ LỤA KHO TIÊU CHIÊN MẮM (Đậm đà đưa cơm)", "instruction": "Món này biến miếng giò lụa mềm mượt trở nên giòn dai bên ngoài, thấm đẫm sốt mặn ngọt bên trong.\n1. Chuẩn bị:\nGiò lụa: 1 cây 250g (Cắt miếng tam giác hoặc thanh dài vừa ăn).\nGia vị: Nước mắm, đường, tương ớt, tiêu đen giã dập, hành tím, tỏi băm.\n2. Cách làm:\n<b>Bước 1:</b> (Áp chảo): Cho chút dầu vào chảo, chiên sơ các mặt miếng giò cho đến khi hơi vàng nhẹ và săn lại. Vớt ra để ráo.\n<b>Bước 2:</b> (Làm sốt): Pha hỗn hợp gồm: 2 muỗng nước mắm + 1 muỗng đường + 1 muỗng tương ớt + 2 muỗng nước lọc.\n<b>Bước 3:</b> (Rim giò): Phi thơm hành tỏi, đổ hỗn hợp sốt vào đun sôi. Cho giò vào đảo đều ở lửa nhỏ đến khi sốt kẹo lại, bám đều vào miếng giò.\n<b>Bước 4:</b> Rắc thật nhiều tiêu đen và hành lá lên trên. Ăn cùng cơm nóng là \"hết sẩy\".\n\n🥗"}, {"name": "Món 2: NỘM GIÒ LỤA NGŨ SẮC (Thanh mát, chống ngán)", "instruction": "Nếu bạn muốn một món khai vị hoặc món ăn nhẹ bụng:\n<b>Nguyên liệu:</b>\n• Giò lụa 250g thái sợi, xoài xanh, cà rốt, dưa leo (cắt sợi), rau thơm.\n• Nước trộn: Mắm, đường, chanh, tỏi, ớt (tỉ lệ 1:1:1).\n<b>Cách làm:</b>\n• Trộn đều tất cả nguyên liệu với nước sốt, rắc thêm lạc rang (đậu phộng) là xong."}]}' WHERE slug = 'gio-lua-250gr';

-- Cập nhật Nem chua
UPDATE products SET recipes = '{"title": "Mồi bén đêm khuya! Nem chua rim tỏi ớt – Sự kết hợp \"không lối thoát\".", "items": [{"name": "🌶️ NEM CHUA RIM TỎI ỚT LẮC MUỐI NHUYỄN", "instruction": "Nếu đã chán cách ăn bóc vỏ chấm tương truyền thống, hãy thử ngay công thức \"bùng nổ\" vị giác này:\n1. Nguyên liệu:\nNem chua: 200g (Cắt miếng vuông vừa ăn hoặc để nguyên thanh nhỏ).\nTỏi tép: 50g (Để nguyên tép hoặc cắt đôi nếu tép lớn).\nGia vị: Nước mắm, đường, ớt bột, tương ớt.\n2. Cách làm:\n<b>Bước 1:</b> (Chiên tỏi): Đun nóng dầu, cho tỏi tép vào chiên ở lửa vừa đến khi tỏi chuyển màu vàng giòn thì vớt ra.\n<b>Bước 2:</b> (Chiên nem): Dùng lại chảo dầu đó, thả nem chua vào chiên thật nhanh khoảng 1-2 phút cho xém mặt (Đừng chiên lâu nem sẽ bị cứng).\n<b>Bước 3:</b> (Lắc sốt): Pha 1 muỗng mắm + 1 muỗng đường + 1 muỗng tương ớt. Đổ vào chảo rim cho kẹo lại.\n<b>Bước 4:</b> Trộn nem chua, tỏi phi giòn và rắc thêm chút ớt bột hoặc muối Tây Ninh. Món này uống kèm với một ly bia lạnh thì quả thật là \"chân ái\"."}]}' WHERE slug = 'nem-chua-200gr';

-- Cập nhật Nem nướng
UPDATE products SET recipes = '{"title": "Cuối tuần tụ tập, trổ tài làm Nem nướng bánh hỏi chuẩn vị miền Trung.", "items": [{"name": "Hướng dẫn chế biến", "instruction": "CUỐN NEM NƯỚNG BÁNH HỎI MỠ HÀNH\nKhỏi cần ra quán, bạn có thể tự tay chuẩn bị mâm cuốn đầy đặn và sang trọng cho gia đình.\n1. Chuẩn bị:\nNem nướng: 400g.\nBánh hỏi (hoặc bún tươi), bánh tráng cuốn.\nRau sống: Xà lách, dưa leo, chuối chát, khế, tía tô, diếp cá.\nMỡ hành: Hành lá thái nhỏ, rưới dầu ăn đun sôi thật nóng vào.\nNước chấm: Tương đậu phộng xay nhuyễn nấu với gan heo băm (sốt đặc), hoặc đơn giản nhất là mắm nêm chua ngọt chanh tỏi ớt.\n2. Cách làm:\n<b>Bước 1:</b> (Làm nóng nem): Vì nem đã chín sẵn, bạn chỉ cần cho vào nồi chiên không dầu hoặc áp chảo lửa nhỏ khoảng 5-7 phút cho nem xém xém, tươm mỡ và tỏa mùi thơm nức mũi.\n<b>Bước 2:</b> (Bày biện): Xếp bánh hỏi ra đĩa, quết mỡ hành và rắc đậu phộng rang lên. Xếp nem nướng nóng hổi bên cạnh.\n<b>Bước 3:</b> Dùng bánh tráng, lót rau sống, đặt 1 miếng nem nướng, 1 miếng bánh hỏi mỡ hành, cuộn lại và chấm ngập vào chén sốt. Vị béo của mỡ hành, thơm của nem và chát nhẹ của chuối khế hòa quyện tạo nên trải nghiệm ẩm thực bùng nổ."}]}' WHERE slug = 'nem-nuong-400gr';

-- Cập nhật Bánh xếp hải sản CJ Bibigo
UPDATE products SET recipes = '{"title": "Món áp chảo vạn người mê - Bí quyết có lớp vỏ bánh giòn tan như ngoài tiệm!", "items": [{"name": "Hướng dẫn chế biến", "instruction": "🍤 HÁ CẢO CHIÊN NƯỚC (PAN-FRIED MANDU)\nCách chế biến này giúp mặt dưới của bánh giòn rụm, mặt trên lại mềm dai, phần nhân hải sản bên trong thì giữ được độ mọng nước.\n1. Chuẩn bị:\nBánh xếp hải sản CJ Bibigo: 1 gói 350g.\nDầu ăn, nước lọc.\nNước chấm: 2 muỗng nước tương, 1 muỗng giấm đen (hoặc giấm gạo), chút dầu mè và gừng thái chỉ.\n2. Cách làm:\n<b>Bước 1:</b> Làm nóng chảo chống dính với khoảng 1-2 muỗng canh dầu ăn.\n<b>Bước 2:</b> Xếp bánh (KHÔNG rã đông) vào chảo. Chiên ở lửa vừa trong khoảng 1-2 phút cho đến khi phần đáy bánh hơi vàng.\n<b>Bước 3:</b> Đổ vào chảo khoảng 50ml nước (mức nước cao khoảng 1/3 miếng bánh). Đậy nắp kín ngay lập tức.\n<b>Bước 3:</b> (Tạo màng giòn): Để lửa vừa trong khoảng 5-6 phút cho đến khi nước cạn hoàn toàn và lớp bột năng dưới đáy chuyển sang màu vàng giòn, kết dính các miếng bánh lại với nhau.\n<b>Bước 4:</b> Úp ngược đĩa vào chảo và lật bánh ra. Bạn sẽ có một đĩa bánh xếp hải sản vàng rụm, đẹp mắt như ở nhà hàng Dimsum."}]}' WHERE slug = 'banh-xep-bibigo-haisan';

-- Cập nhật Bánh xếp thịt CJ Bibigo
UPDATE products SET recipes = '{"title": "Đừng chỉ chiên! Đây là cách ăn Bánh xếp Bibigo mà fan cứng chưa chắc đã biết.", "items": [{"name": "Hướng dẫn chế biến", "instruction": "🌶️ BÁNH XẾP LẮC SỐT CAY TƯƠNG ĐEN\nCông thức này biến món bánh xếp truyền thống thành một món ăn vặt \"\"đậm đà\"\", cực kỳ kích thích vị giác cho buổi xế hoặc xem phim.\n1. Chuẩn bị:\nBánh xếp thịt Bibigo: 1 gói 350g.\nNguyên liệu sốt: 1 muỗng canh tương đen, 1 muỗng cà phê ớt bột (Hàn Quốc), 1 muỗng canh nước tương, 1 muỗng cà phê đường, chút tỏi băm và dầu mè.\nĂn kèm: Hành lá thái nhỏ, mè trắng rang.\n2. Cách làm:\n<b>Bước 1:</b> (Chiên giòn): Cho bánh xếp vào nồi chiên không dầu ở 180°C trong 10-12 phút (hoặc chiên ngập dầu) cho đến khi lớp vỏ bánh phồng rộp và giòn rụm.\n<b>Bước 2:</b> (Làm sốt): Trong lúc đợi bánh, bạn phi thơm tỏi băm, cho tất cả các gia vị làm sốt vào chảo, khuấy đều ở lửa nhỏ đến khi sốt sôi lăm tăm và sệt lại.\n<b>Bước 3:</b> (Lắc vị): Trút bánh xếp đã chiên giòn vào chảo sốt. Đảo thật nhanh tay trong khoảng 30 giây để sốt áo đều một lớp bóng bẩy bên ngoài từng chiếc bánh.\n<b>Bước 4:</b> Bày ra đĩa, rắc hành lá và mè rang lên. Cắn một miếng, lớp vỏ ngoài giòn tan thấm vị mặn ngọt cay cay, bên trong là nhân thịt rau củ mềm ẩm tuôn trào. Cực kỳ bắt miệng!"}]}' WHERE slug = 'banh-xep-bibigo-thit';